# Generated by Django 4.1.3 on 2022-12-04 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=512)),
                ('summary', models.TextField()),
                ('date_published', models.DateTimeField()),
                ('author', models.CharField(max_length=256)),
            ],
        ),
    ]
